// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"
)

type Incomeexpense struct {
	ID       sql.NullString
	Userid   sql.NullString
	Type     sql.NullString
	Category sql.NullString
	Currency sql.NullString
	Amount   sql.NullFloat64
	Date     sql.NullString
}
