// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: internal/protos/reportproto/report.proto

package reportproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncomeExpenseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalIncome   float32 `protobuf:"fixed32,1,opt,name=totalIncome,proto3" json:"totalIncome,omitempty"`
	TotalExpenses float32 `protobuf:"fixed32,2,opt,name=totalExpenses,proto3" json:"totalExpenses,omitempty"`
	NetSavings    float32 `protobuf:"fixed32,3,opt,name=netSavings,proto3" json:"netSavings,omitempty"`
}

func (x *IncomeExpenseResponse) Reset() {
	*x = IncomeExpenseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncomeExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeExpenseResponse) ProtoMessage() {}

func (x *IncomeExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeExpenseResponse.ProtoReflect.Descriptor instead.
func (*IncomeExpenseResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{0}
}

func (x *IncomeExpenseResponse) GetTotalIncome() float32 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *IncomeExpenseResponse) GetTotalExpenses() float32 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *IncomeExpenseResponse) GetNetSavings() float32 {
	if x != nil {
		return x.NetSavings
	}
	return 0
}

type SpendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *SpendingRequest) Reset() {
	*x = SpendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingRequest) ProtoMessage() {}

func (x *SpendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingRequest.ProtoReflect.Descriptor instead.
func (*SpendingRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{1}
}

func (x *SpendingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SpendingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category   string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Totalspent float32 `protobuf:"fixed32,2,opt,name=totalspent,proto3" json:"totalspent,omitempty"`
}

func (x *SpendingResponse) Reset() {
	*x = SpendingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingResponse) ProtoMessage() {}

func (x *SpendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingResponse.ProtoReflect.Descriptor instead.
func (*SpendingResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{2}
}

func (x *SpendingResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SpendingResponse) GetTotalspent() float32 {
	if x != nil {
		return x.Totalspent
	}
	return 0
}

type ListSpendingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spent []*SpendingResponse `protobuf:"bytes,1,rep,name=spent,proto3" json:"spent,omitempty"`
}

func (x *ListSpendingResponse) Reset() {
	*x = ListSpendingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSpendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpendingResponse) ProtoMessage() {}

func (x *ListSpendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpendingResponse.ProtoReflect.Descriptor instead.
func (*ListSpendingResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{3}
}

func (x *ListSpendingResponse) GetSpent() []*SpendingResponse {
	if x != nil {
		return x.Spent
	}
	return nil
}

type FromTillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime string `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FromTillRequest) Reset() {
	*x = FromTillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromTillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromTillRequest) ProtoMessage() {}

func (x *FromTillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromTillRequest.ProtoReflect.Descriptor instead.
func (*FromTillRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{4}
}

func (x *FromTillRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *FromTillRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *FromTillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FromTillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmount float32 `protobuf:"fixed32,1,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
}

func (x *FromTillResponse) Reset() {
	*x = FromTillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_reportproto_report_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromTillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromTillResponse) ProtoMessage() {}

func (x *FromTillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_reportproto_report_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromTillResponse.ProtoReflect.Descriptor instead.
func (*FromTillResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_reportproto_report_proto_rawDescGZIP(), []int{5}
}

func (x *FromTillResponse) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_internal_protos_reportproto_report_proto protoreflect.FileDescriptor

var file_internal_protos_reportproto_report_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x15, 0x49, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78,
	0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6e,
	0x65, 0x74, 0x53, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0a, 0x6e, 0x65, 0x74, 0x53, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x2a, 0x0a, 0x0f, 0x53,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x0f, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10,
	0x46, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0xba, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x12, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x62, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x2e, 0x53, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x46, 0x72, 0x6f,
	0x6d, 0x54, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x46,
	0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_reportproto_report_proto_rawDescOnce sync.Once
	file_internal_protos_reportproto_report_proto_rawDescData = file_internal_protos_reportproto_report_proto_rawDesc
)

func file_internal_protos_reportproto_report_proto_rawDescGZIP() []byte {
	file_internal_protos_reportproto_report_proto_rawDescOnce.Do(func() {
		file_internal_protos_reportproto_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_reportproto_report_proto_rawDescData)
	})
	return file_internal_protos_reportproto_report_proto_rawDescData
}

var file_internal_protos_reportproto_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_protos_reportproto_report_proto_goTypes = []any{
	(*IncomeExpenseResponse)(nil), // 0: IncomeExpenseResponse
	(*SpendingRequest)(nil),       // 1: SpendingRequest
	(*SpendingResponse)(nil),      // 2: SpendingResponse
	(*ListSpendingResponse)(nil),  // 3: ListSpendingResponse
	(*FromTillRequest)(nil),       // 4: FromTillRequest
	(*FromTillResponse)(nil),      // 5: FromTillResponse
}
var file_internal_protos_reportproto_report_proto_depIdxs = []int32{
	2, // 0: ListSpendingResponse.spent:type_name -> SpendingResponse
	1, // 1: ReportService.SpendingbyCategory:input_type -> SpendingRequest
	1, // 2: ReportService.IncomeExpense:input_type -> SpendingRequest
	4, // 3: ReportService.FromTill:input_type -> FromTillRequest
	3, // 4: ReportService.SpendingbyCategory:output_type -> ListSpendingResponse
	0, // 5: ReportService.IncomeExpense:output_type -> IncomeExpenseResponse
	5, // 6: ReportService.FromTill:output_type -> FromTillResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protos_reportproto_report_proto_init() }
func file_internal_protos_reportproto_report_proto_init() {
	if File_internal_protos_reportproto_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_reportproto_report_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IncomeExpenseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_reportproto_report_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SpendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_reportproto_report_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SpendingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_reportproto_report_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListSpendingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_reportproto_report_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FromTillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_reportproto_report_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FromTillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_reportproto_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_reportproto_report_proto_goTypes,
		DependencyIndexes: file_internal_protos_reportproto_report_proto_depIdxs,
		MessageInfos:      file_internal_protos_reportproto_report_proto_msgTypes,
	}.Build()
	File_internal_protos_reportproto_report_proto = out.File
	file_internal_protos_reportproto_report_proto_rawDesc = nil
	file_internal_protos_reportproto_report_proto_goTypes = nil
	file_internal_protos_reportproto_report_proto_depIdxs = nil
}
